apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
type: Opaque
data:
  NEXTAUTH_SECRET: <base64-encoded-nextauth-secret>
  JWT_SECRET: <base64-encoded-jwt-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  root-username: <base64-encoded-username>
  root-password: <base64-encoded-password> 